### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by jgsheffer** [eviltypha/Ranobes-Scraper#2]
I appear to be getting a 403 forbidden error after entering the url.  
I was able to get it to work by manually pulling the cookie out of my browser session and adding it to the header for the requests

**Comment by eviltypha** [comment]
I haven't faced this issue yet, but anyways I've added a workaround by extracting cookies and using them in the code. Do test it out and let me know.

**Comment by HarnoorSingh79** [comment]
@eviltypha I am facing 403 forbidden error after entering the url? what should i do?

**Comment by eviltypha** [comment]
Hi @HarnoorSingh79, are you able to access the website through your browser? Try using a VPN.

**Comment by SirGryphin** [comment]
@eviltypha still getting this error, I can load site fine in web browser.
```python
$ python main.py
Enter URL : https://ranobes.net/novels1/450143-the-daily-life-of-the-immortal-king-v33632.html

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Github\ranobes-scraper-evil\main.py", line 28, in <module>
    webpage = urlopen(req).read()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Lattaz** [comment]
I'm getting the same 403 forbidden error, not even cyberghost vpn is working.

**Comment by Demianeen** [comment]
Hi everybody. All the pages on ranobe.net give me
![CleanShot 2024-03-13 at 10 08 41@2x](https://github.com/eviltypha/Ranobes-Scraper/assets/51330172/27b04c5c-b6c8-491b-8a4c-9850309135a7)

Has it happened to anyone else?
